Feature/codestyle embed c ru rebase
wirenboard/codestyle pull request #18
Opened 2022-05-04 11:59 UTC by RLOVD

https://github.com/wirenboard/codestyle/pull/7

2022-05-04 12:33 UTC, nikitoz236 requested changes

2022-05-04 12:33 UTC, nikitoz236 commented on embedded_c.en.md
> +## Обозначение и скобки
Расстановка скобок

2022-05-04 12:33 UTC, nikitoz236 commented on embedded_c.en.md
> +Всегда скобки, даже когда тело функции 1 строчка и даже когда его нет:
тело блока

2022-05-04 13:17 UTC, pgasheev reviewed
Мне если честно не очень нравится стиль, он больше похож на разговорный, чем на документ. Где-то предложения не согласованы, ошибки встречаются. Не знаю, нужно заострять на этом внимание

2022-05-04 13:17 UTC, pgasheev commented on embedded_c.en.md
> +Всегда скобки, даже когда тело функции 1 строчка и даже когда его нет:
Тут вроде про циклы/условия речь, а про тело функции и скобки вокруг него было выше

2022-05-04 13:17 UTC, pgasheev commented on embedded_c.en.md
> +Перенос скобки на следущую строку начала определения осуществляется в функциях, в остальном нет.
следущую -> следующую

2022-05-04 13:28 UTC, nikitoz236 commented on embedded_c.en.md
> +код
дак у нас както нет особо doxygen, нужен он нам ?

2022-05-04 13:31 UTC, pgasheev commented on embedded_c.en.md
> +код
Коллеги используют, в том же wb-mqtt-serial. Плюсы вижу в том, что vscode это хорошо подсвечивает и подсказывает. Да и шаблон комментария автоматом вставляет

2022-05-04 13:44 UTC, RLOVD commented on embedded_c.en.md
> +2. Пробелами разделяются знаки ``` + != = == - / ```... с двух сторон.
Можно так  "знаки арифметических, логических, бинарных операций (+ != = == - /  т.д.)

2022-05-04 13:53 UTC, pgasheev commented on embedded_c.en.md
> +2. Пробелами разделяются знаки ``` + != = == - / ```... с двух сторон.
Вот после логического `!` и битового `~` не надо пробелы. Общим словом можно назвать "унарные операции", между ними и переменной пробела не надо. 

Знаки бинарных операций отделяются от переменных пробелами, а знаки унарных операций - нет.

```
a += b / c;
c++;
c &= ~d;
```

2022-05-04 18:10 UTC, pgasheev commented on embedded_c.en.md
> +Скобки ставятся всегда, даже когда тело блока 1 строчка и даже когда его нет:
Слово-в-слово 206 строчка

2022-05-05 06:49 UTC, RLOVD commented on embedded_c.en.md
> +Скобки ставятся всегда, даже когда тело блока 1 строчка и даже когда его нет:
там про тело функции, здесь про тело блока условия

сам же писал ["Тут вроде про циклы/условия речь, а про тело функции и скобки вокруг него было выше"](https://github.com/wirenboard/codestyle/pull/18#discussion_r864801660)

2022-05-05 07:14 UTC, pgasheev commented on embedded_c.en.md
> +Скобки ставятся всегда, даже когда тело блока 1 строчка и даже когда его нет:
Ну да, одним словом отличается, не заметил. Но все равно, кажется можно это одним предложением описать в одной строчке, чем два раза дублировать. Да и функция без тела вроде не бывает, а значит там без скобок в принципе не обойтись и писать про них в случае с функцией смысла нет.

2022-05-06 12:37 UTC, pgasheev approved these changes

2022-05-11 07:52 UTC, merged