add debian-release-upgrade guideline (ru)
wirenboard/codestyle pull request #21
Opened 2022-07-07 17:29 UTC by webconn

Добавил гайдлайн по обновлению дистрибутива Debian в процессе выпуска нового релиза. Там описана сама процедура выпуска релиза на новом дистрибутиве, переключение сборки пакетов под новый дистрибутив, а также правила бэкпортирования изменений в старый релиз, если такие понадобятся.

@evgeny-boger @vdromanov хочу, чтобы вы посмотрели на предмет адекватности с вашей точки зрения.

И в целом всем ревьюверам предлагаю ознакомиться, в особенности в части бэкпортирования.

2022-07-08 05:19 UTC, KraPete commented
1. Мы под stretch собирать уже ничего не будем? Новые релизы на stretch будут?
2. Код для stretch и bullseye в git будет в разных ветках?

2022-07-08 10:15 UTC, webconn commented
> 1. Мы под stretch собирать уже ничего не будем? Новые релизы на stretch будут?

Новых релизов под stretch больше не планируем, 2207 будет последним.

> 2. Код для stretch и bullseye в git будет в разных ветках?

Соответственно, после заморозки testing для 2207 код в master/main будет для bullseye по умолчанию, а для stretch будут доезжать патчи в ветку `release/wb-2207/wbX-stretch`

2022-11-14 10:28 UTC, KraPete commented
@webconn Это ещё актуально?

2022-11-14 11:37 UTC, webconn commented
Ну да, мы по этой инструкции на булзай переезжали (примерно, я уточню, если что-то по-другому было)

2022-11-22 11:01 UTC, KraPete requested changes
Никита хочет актуализировать

2023-04-17 07:51 UTC, webconn commented on guidelines/debian-release-upgrade.ru.md
> + 5. В этот момент можно переназначить таргеты `current-*` в `devenv` на новый
Уточнил в тексте

2023-04-17 07:51 UTC, webconn commented on guidelines/debian-release-upgrade.ru.md
> + 4. Создаём для нового дистрибутива релиз `testing`. Его можно сразу назначит
Вроде поправил всё

2023-04-17 07:51 UTC, webconn commented
Уточнил гайдлайн по мотивам реального процесса перехода, можно смотреть

2023-04-18 05:52 UTC, KraPete approved these changes

2023-04-24 10:47 UTC, merged