Feature/50392 git workflow additional info
wirenboard/codestyle pull request #22
Opened 2022-07-13 05:42 UTC by vdromanov

Поправил неактуальное; завёз дополнения из задачки и с первой ретроспективы

2022-07-19 12:52 UTC, webconn requested changes
Ещё общие предложения:

1. Написать более формально (скриншотики, женкинс, вот это всё).
2. `Настоятельно рекомендуется`, `желательно` - это как-то не обязывает пользоваться правилами. На мой вкус, правила либо есть, либо их нет.

2022-07-19 12:52 UTC, webconn commented on workflow.md
> +**Используем только консольный клиент git!**
Не думаю, что это обязательно

2022-07-19 12:52 UTC, webconn commented on workflow.md
> +_Настоятельно рекомендуется писать сообщения коммитам на английском в повелительном наклонении. Образец: "add <что_было_добавлено>" - ок. "add**ed** <что_было_добавлено>" или "<что_было_добавлено> is
Ещё оставь тут ссылки на доводы за такую нотацию

2022-07-19 12:52 UTC, webconn commented on workflow.md
> +  Если ``master/main`` уже убежал - нужно сделать ``git pull origin master`` и порешать merge-конфликты.
Там `git merge master` ещё не понадобится?

2022-07-19 12:52 UTC, webconn commented on workflow.md
> +  - Когда все правки внесены _(и изменения, прилетевшие с ними, проверены)_ - запушить ветку, из которой открыт PR, и нажать на "re-request review" сверху в интерфейсе гитхаба.
Эта кнопка выглядит как иконочка рядом с ревьюверами, тут лучше на это указать. Ну так, на всякий случай

2022-07-19 12:52 UTC, webconn commented on workflow.md
> +Код пишем одинаково. Что-то по embedded_C/C++/Python описано в .md рядом, что-то выяснится после ревью пулл-реквестов. Если чего-то нет в стайлгайде, то лучше посмотреть как написано рядом.
Давай ссылки сюда лучше

2022-07-20 12:46 UTC, KraPete commented on workflow.md
> +_Настоятельно рекомендуется писать сообщения коммитам на английском в повелительном наклонении. Образец: "add <что_было_добавлено>" - ок. "add**ed** <что_было_добавлено>" или "<что_было_добавлено> is
Тогда уж adds.

2022-07-20 12:48 UTC, KraPete commented on workflow.md
> +  - Слияние выполняет автор PR после того, как все ревьюверы поставили approve.
Мы ж жоговорились, что одного ревьювера достаточно?

2022-07-20 12:50 UTC, webconn commented on workflow.md
> +_Настоятельно рекомендуется писать сообщения коммитам на английском в повелительном наклонении. Образец: "add <что_было_добавлено>" - ок. "add**ed** <что_было_добавлено>" или "<что_было_добавлено> is
Не, там другая идея была: https://cbea.ms/git-commit/

2022-07-20 14:03 UTC, webconn commented on workflow.md
> +_Настоятельно рекомендуется писать сообщения коммитам на английском в повелительном наклонении. Образец: "add <что_было_добавлено>" - ок. "add**ed** <что_было_добавлено>" или "<что_было_добавлено> is
Это я выше и предложил :)

2022-07-21 23:38 UTC, vdromanov commented on workflow.md
> +**Используем только консольный клиент git!**
думаю, стоит это оставить, т.к. у коллег с проверки не раз были проблемы из-за сторонних клиентов

написал менее категорично

2022-07-21 23:38 UTC, vdromanov commented on workflow.md
> +_Настоятельно рекомендуется писать сообщения коммитам на английском в повелительном наклонении. Образец: "add <что_было_добавлено>" - ок. "add**ed** <что_было_добавлено>" или "<что_было_добавлено> is
готово

2022-07-21 23:39 UTC, vdromanov commented on workflow.md
> +  Если ``master/main`` уже убежал - нужно сделать ``git pull origin master`` и порешать merge-конфликты.
там add и commit надо
дописал

2022-07-21 23:39 UTC, vdromanov commented on workflow.md
> +  - Когда все правки внесены _(и изменения, прилетевшие с ними, проверены)_ - запушить ветку, из которой открыт PR, и нажать на "re-request review" сверху в интерфейсе гитхаба.
готово

2022-07-21 23:39 UTC, vdromanov commented on workflow.md
> +Код пишем одинаково. Что-то по embedded_C/C++/Python описано в .md рядом, что-то выяснится после ревью пулл-реквестов. Если чего-то нет в стайлгайде, то лучше посмотреть как написано рядом.
готово

2022-07-21 23:39 UTC, vdromanov commented on workflow.md
> +  - Слияние выполняет автор PR после того, как все ревьюверы поставили approve.
кстати да
поправил

2022-07-25 09:29 UTC, webconn commented on workflow.md
> +  - Слияние выполняет автор PR после того, как все ревьюверы поставили approve.
А я вот всё-таки не согласен, и писал в первой версии workflow про всех ревьюверов не просто так.

Сейчас у нас "достаточно одного ревьювера" - это скорее договорённость, которая основана на том, что так потенциально быстрее всё проходит. Когда мы начнём делать ревью внутри команды, не завязываясь на меня и Женю так плотно, проблема должна стать поменьше.

Иногда просто действительно хочется, чтобы несколько человек обязательно посмотрели изменения, и в таком случае надо дожидаться всех ревьюверов.

Можно было бы оставить лазейку в духе "наотмечать кучу людей - дождаться кого-то одного - удалить остальных и влить", но она мне не нравится, потому что насыпет уведомлений без дела.

Короче, лучше оставить тут слово "все" и начать этому правилу следовать, чем убирать его и оставлять тут неопределённость.

2022-08-18 13:42 UTC, ekateluv commented
Субьективно мне не очень нравятся некоторые пункты вот тут, хочу немного обсудить
```
4. Перед подготовкой PR нужно сделать следующее:
  - убедиться, что история линейна (ветка - последовательность из одного или нескольких коммитов без мержей с другими ветками, в т.ч. `main` (или `master`));
  - в ветке адекватное количество коммитов (часто достаточно одного, желательно - до 5);
  - каждый коммит имеет смысловую нагрузку и соответствует какому-то атомарному изменению;
  - одно и то же место в коде не должно изменяться разными коммитами;
  - если потребовалось переименование/перемещение файлов, оно должно быть выполнено отдельным коммитом
  ```
В ветке адекватное количество коммитов, желательно до 5ти - мне кажется количество коммитов зависит от задачи, на больших задачах за 5 коммитов сделать все трудно. Я лично вобще испытала некий стресс, когда мне выдали задачу про RPC и вот тут потом написано 5 коммитов...
Одно и то же место в коде не должно изменяться разными коммитами - а почему нет? Сделал что-нибудь одним способом, сделал коммит, потом передумал, сделал другим, сделал коммит, вдруг потом к первому варианту нужно будет вернуться, пока работаешь. Или просто посмотреть как было еще раз. Я понимаю, чем обусловлено это требование, но мне кажется оно не очень реалистичное...

2022-08-18 14:02 UTC, webconn commented
> В ветке адекватное количество коммитов, желательно до 5ти - мне кажется количество коммитов зависит от задачи, на больших задачах за 5 коммитов сделать все трудно. Я лично вобще испытала некий стресс, когда мне выдали задачу про RPC и вот тут потом написано 5 коммитов...

Я напомню, что это касается подготовки PR к открытию, а не вливанию. То есть в ходе обсуждения и внесения правок коммитов может получиться много, и это нормально.

> Одно и то же место в коде не должно изменяться разными коммитами - а почему нет? Сделал что-нибудь одним способом, сделал коммит, потом передумал, сделал другим, сделал коммит, вдруг потом к первому варианту нужно будет вернуться, пока работаешь. Или просто посмотреть как было еще раз. Я понимаю, чем обусловлено это требование, но мне кажется оно не очень реалистичное...

Опять же, в ходе внесения правок во время ревью это нормально. Но в самом начале ревьюеверам не обязательно будет интересно смотреть на ход изменения мысли, там речь идёт о самодостаточном инкременте

2022-08-18 14:03 UTC, ekateluv requested changes

2022-08-18 14:03 UTC, ekateluv commented on workflow.md
> +  - Сразу удаляй ненужные ветки (через кнопку на гитхабе) - не заставляй Jenkins страдать!
Можно уточнить где кнопка - "Через кнопку Delete branch, которая появится после слияния ветки"

2022-08-18 14:09 UTC, ekateluv commented
Еще вспомнила - у нас нет описания рецепта, что делать, если создаешь новый репозиторий

2022-08-29 11:41 UTC, vdromanov commented on workflow.md
> +_Удобнее - пользоваться консольным клиентом git!_
подрасписал

2022-08-29 11:41 UTC, vdromanov commented on workflow.md
> +  - Когда все правки внесены _(и изменения, прилетевшие с ними, проверены)_ - сделать push ветки, из которой открыт PR, и нажать на "re-request review" (сверху в интерфейсе гитхаба; рядом с ревьювера
ну тут довольно капитанский совет из серии "внес правки - запусти, хотя бы"
товарищи из тест-сьюта этим точно страдали; у нас, надеюсь, такого нет:)

расписал

2022-08-29 11:41 UTC, vdromanov commented on workflow.md
> +  - Слияние выполняет автор PR после того, как все ревьюверы поставили approve.
done

2022-08-29 11:41 UTC, vdromanov commented on workflow.md
> +    (если настроен CI для репозитория). Если Jenkins ругается - не стесняемся читать логи. Не получилось разобраться быстро - дёргаем ответственных за Jenkins.
готово

2022-08-29 11:41 UTC, vdromanov commented on workflow.md
> +  - Сразу удаляй ненужные ветки (через кнопку на гитхабе) - не заставляй Jenkins страдать!
готово

2022-09-05 05:31 UTC, webconn requested changes
В остальном вроде хорошо

2022-09-05 05:31 UTC, webconn commented on workflow.md
> +  - Если в процессе исправлений нужно сделать push (например, чтобы запустить CI) - `git checkout -b tmp/<username>/<что-то_осмысленное>` и push уже её. Так ревьюверам не будут приходить лишние уведо
Я вот не понял, что тут имелось в виду.

```
Если в процессе исправлений понадобилось что-то проверить в сборке на CI (например, починить упавшую сборку или тесты), используйте для этого временную ветку (вида tmp/username/branch_name), чтобы не присылать ревьюверам лишних уведомлений. После использования не забудьте удалить ветку.
```

2022-09-05 11:01 UTC, vdromanov commented on workflow.md
> +  - Если в процессе исправлений нужно сделать push (например, чтобы запустить CI) - `git checkout -b tmp/<username>/<что-то_осмысленное>` и push уже её. Так ревьюверам не будут приходить лишние уведо
готово

2022-09-06 07:10 UTC, webconn approved these changes

2022-09-06 14:07 UTC, merged