Added guidline for setup chroot for build
wirenboard/codestyle pull request #25
Opened 2022-08-17 21:04 UTC by rkochkin

Добавил описание как из fit образа системы извлечь и настроить chroot rootfs для сборки C++ проектов.
Возможно какие то вещи можно автоматизировать или сделать иначе.

2022-08-18 12:27 UTC, ekateluv commented on guidelines/chroot-build-environment.md
> +dumpimage -T flat_dt -p 3 -o rootfs.tar.gz <image>.fit
На этом месте у меня перестало получаться.
Я сходила вот сюда [Jenkins](https://jenkins.wirenboard.com/job/pipelines/job/build-image/), нажала Собрать с параметрами, в разделе BOARD выбрала 6х, в DEBIAN_RELEASE - bullseye. Больше ничего не писала и не выбирала, нажала Собрать.
Попытка выполнить эту команду с этими образами закончилась вот так:
```
wb@wb-Latitude-3400:~/Bullseye$ dumpimage -T flat_dt -p 3 -o rootfs.tar.gz 202208181217_testing_webupd_wb6x.fit
dumpimage: failed to verify header of FIT Image support
dumpimage: Can't extract subimage from 202208181217_testing_webupd_wb6x.fit
```
Образ пробовала собирать дважды, оба раза такая ошибка

2022-08-18 12:51 UTC, webconn commented on guidelines/chroot-build-environment.md
> +dumpimage -T flat_dt -p 3 -o rootfs.tar.gz <image>.fit
Файл хорошо скачался? Почему не взяла просто готовый образ из сохранённых билдов (внизу списка в jenkins)?

2022-08-18 12:53 UTC, KraPete commented on guidelines/chroot-build-environment.md
> +dumpimage -T flat_dt -p 3 -o rootfs.tar.gz <image>.fit
```
pete@home:~/tttt$ dumpimage -T flat_dt -p 3 -o rootfs.tar.gz 202208181217_testing_webupd_wb6x.fit
Extracted:
 Image 3 (rootfs)
  Description:  Root filesystem tarball
  Created:      Thu Aug 18 17:18:16 2022
  Type:         Unknown Image
  Compression:  uncompressed
  Data Size:    197307718 Bytes = 192683.32 KiB = 188.17 MiB
  Hash algo:    sha1
  Hash value:   d05063f4d8eee34750f8f14a600026b9f871c166
```

2022-08-18 12:55 UTC, KraPete commented on guidelines/chroot-build-environment.md
> +dumpimage -T flat_dt -p 3 -o rootfs.tar.gz <image>.fit
УМВР, только мне потребовалось больше линков из `/dev` сделать. Я это в PR Ромы про `chroot_this.sh` написал.

2022-08-18 12:57 UTC, ekateluv commented on guidelines/chroot-build-environment.md
> +dumpimage -T flat_dt -p 3 -o rootfs.tar.gz <image>.fit
Скачался хорошо, сама собрала потому что не заметила что есть готовые. На готовом, кстати, у меня получилось то же самое, то есть ничего не получилось

2022-08-18 13:07 UTC, ekateluv commented on guidelines/chroot-build-environment.md
> +dumpimage -T flat_dt -p 3 -o rootfs.tar.gz <image>.fit
> УМВР, только мне потребовалось больше линков из `/dev` сделать. Я это в PR Ромы про `chroot_this.sh` написал.

Напиши, пожалуйста, конкретнее, что еще нужно сделать. Прикрепи ссылку на PR

2022-08-18 13:10 UTC, KraPete commented on guidelines/chroot-build-environment.md
> +dumpimage -T flat_dt -p 3 -o rootfs.tar.gz <image>.fit
> > УМВР, только мне потребовалось больше линков из `/dev` сделать. Я это в PR Ромы про `chroot_this.sh` написал.
> 
> Напиши, пожалуйста, конкретнее, что еще нужно сделать. Прикрепи ссылку на PR

Дак это потом потребуется, уже внутри chroot. https://github.com/wirenboard/wb-configs/pull/61

2022-08-18 13:57 UTC, KraPete commented on guidelines/chroot-build-environment.md
> +dumpimage -T flat_dt -p 3 -o rootfs.tar.gz <image>.fit
```
dumpimage version 2021.01+dfsg-3ubuntu0~20.04.4
```
Всё ок

2022-08-24 10:59 UTC, rkochkin commented on guidelines/chroot-build-environment.md
> +dumpimage -T flat_dt -p 3 -o rootfs.tar.gz <image>.fit
Добавил примечание

2022-08-24 12:40 UTC, webconn requested changes

2022-08-24 12:40 UTC, webconn commented on guidelines/chroot-build-environment.md
> +* 2021.01+dfsg-5
Так это бы выше написать рядом с установкой `u-boot-tools` (это же ещё иначе догадаться надо, что `dumpimage` в `u-boot-tools`)

2022-08-29 10:50 UTC, rkochkin commented on guidelines/chroot-build-environment.md
> +* 2021.01+dfsg-5
Написал из какого пакета dumpimage

2022-09-06 07:16 UTC, webconn approved these changes

2022-09-08 13:07 UTC, KraPete approved these changes

2022-09-14 15:03 UTC, merged