Update workflow
wirenboard/codestyle pull request #37
Opened 2022-12-05 13:57 UTC by sikmir

2022-12-05 14:03 UTC, lostpoint-ru approved these changes

2022-12-07 06:32 UTC, webconn commented on workflow.md
> +  7. Добавить `README.md` и `LICENSE`
Я бы ещё дописал, что в `debian/control` вместо конкретного мейнтейнера можно вписывать `Wiren Board team <info@wirenboard.com>`, чтобы не тратить силы на попытку придумать подходящую персону. Столкнулись с этим недавно, кажется, что это будет хорошее упрощение (всё равно никто не будет туда смотреть в реальной жизни).

Ну и из этого документа убрать упоминание полезности поля `Maintainer` из `debian/control`. В некоторых репозиториях в этом месте встречаются люди, которые давно не в проекте.

2022-12-07 06:42 UTC, KraPete requested changes

2022-12-07 06:42 UTC, KraPete commented on workflow.md
> +  4. Выключиить `Wikis` и `Projects` в Settings (не используем)
ВключиИть

2022-12-07 06:42 UTC, KraPete commented on workflow.md
> +  7. Добавить `README.md` и `LICENSE`
Надо эталон лицензии, я чё-то каждый раз в замешательстве, что писать

2022-12-07 06:42 UTC, KraPete commented on workflow.md
> +  6. Добавить в коллабораторы `@wirenboard/developers` команду c доступом `Admin`
10 раз прочитал и так и не понял, что тут имелось ввиду

2022-12-07 07:10 UTC, sikmir commented on workflow.md
> +  7. Добавить `README.md` и `LICENSE`
Только это не сюда, а в раздел дебианизации.

2022-12-07 07:15 UTC, sikmir commented on workflow.md
> +  4. Выключиить `Wikis` и `Projects` в Settings (не используем)
поправил

2022-12-07 07:17 UTC, sikmir commented on workflow.md
> +  6. Добавить в коллабораторы `@wirenboard/developers` команду c доступом `Admin`
Переформулировал, так лучше?

2022-12-07 07:19 UTC, KraPete commented on workflow.md
> +  6. Добавить в коллабораторы `@wirenboard/developers` команду c доступом `Admin`
Ага. Я правда, обычно Женю делал админом, а `developers` делал `Write`. Надо ли всех админами делать?

2022-12-07 07:20 UTC, sikmir commented on workflow.md
> +  7. Добавить `README.md` и `LICENSE`
Ну вот та что в codestyle/LICENSE наверное и можно использовать как эталон, если только `Copyright (c) 2016 Contactless Devices, LLC` поправить на актуальный.

2022-12-07 07:25 UTC, sikmir commented on workflow.md
> +  6. Добавить в коллабораторы `@wirenboard/developers` команду c доступом `Admin`
Например создали новую репу, позже когда сделали реализацию другой человек решил поправить Description у репы, без Admin не сможет, придется пинговать Женю.

2022-12-07 07:25 UTC, webconn commented on workflow.md
> +  7. Добавить `README.md` и `LICENSE`
Думаю, можно из `wb-mqtt-serial` взять лицензию и сюда положить. Там лицензия, похожая на MIT, только с ограничением на запуск софта только на нашем железе

2022-12-07 07:26 UTC, webconn commented on workflow.md
> +  6. Добавить в коллабораторы `@wirenboard/developers` команду c доступом `Admin`
Я думаю, можно `developers` сделать `Maintain`, это лишит прав на удаление репозитория при оставлении кучи всего полезного

2022-12-07 07:28 UTC, sikmir commented on workflow.md
> +  7. Добавить `README.md` и `LICENSE`
Но есть же еще всякие утилитки которые используются не на контроллере?

2022-12-07 07:32 UTC, sikmir commented on workflow.md
> +  6. Добавить в коллабораторы `@wirenboard/developers` команду c доступом `Admin`
Да, проверил, с Maintain есть возможность редактировать Description и прочие мелочи.

2022-12-07 07:33 UTC, webconn commented on workflow.md
> +  7. Добавить `README.md` и `LICENSE`
Кажется, их сильно меньше и такие ситуации можно вручную обрабатывать

2022-12-07 07:41 UTC, sikmir commented on workflow.md
> +  7. Добавить `README.md` и `LICENSE`
Добавил что за основу можно взять LICENSE из serial.

2022-12-07 07:50 UTC, KraPete approved these changes

2022-12-07 10:00 UTC, merged

2022-12-07 10:10 UTC, sikmir commented on workflow.md
> +  3. Выключить `Packages` и `Environments` с главной страницы (не используем)
Еще можно выключить Actions, тоже не используем.