update git workflow description
wirenboard/codestyle pull request #5
Opened 2021-05-27 12:49 UTC by webconn

Набросок обновлённого описания git workflow. Чуть позже я ещё сделаю чеклисты для создания PR и для мержа, сейчас хочу посмотреть комментарии насчёт уже написанного.

2021-05-27 13:55 UTC, PeteK12 requested changes

2021-05-27 13:55 UTC, PeteK12 commented on workflow.md
> +  6. Если были внесены изменения, с которыми стоит ознакомиться команде, то нужно добавлять ревьюверов и весь процесс повторяется сначала.
Если тут было обсуждение, то потом будет `<имя ветки>-rebase-rebase` ?

2021-05-28 10:38 UTC, webconn commented on workflow.md
> +  6. Если были внесены изменения, с которыми стоит ознакомиться команде, то нужно добавлять ревьюверов и весь процесс повторяется сначала.
Поменял на `rebaseX` (`rebase1`, `rebase2` и т.д.)

2021-05-28 10:40 UTC, PeteK12 commented
А почему нельзя удалять старую ветку и после ребейза называть новую так же?

2021-05-28 16:43 UTC, webconn commented
Технически можно. Более того, если старый PR перед ребейзом закрыть, то там даже не потеряются изменения и комменты (только что проверил у себя).

Другое дело, что если при ребейзе что-то сломается, могут возникнуть проблемы с тем, чтобы откатиться обратно. В теории в объектах гита останутся старые коммиты, но на них ничего не будет ссылаться в гите и я бы не стал на них рассчитывать.

Потому моё мнение, хоть в истории гита это будет выглядеть не так красиво, но до мержа все доребейзные ветки надо оставлять как есть с сохранением их имён.

2021-05-29 05:55 UTC, PeteK12 commented
Может, тогда после слияния удалять их?

2021-05-29 19:22 UTC, webconn commented
> Может, тогда после слияния удалять их?

Согласен, добавил это в инструкцию.

2021-05-31 05:52 UTC, PeteK12 approved these changes

2021-06-04 11:43 UTC, evgeny-boger requested changes

2021-06-04 11:51 UTC, webconn commented on workflow.md
> +  3. Делаем что-то в ветке. До того, как был создан PR, с веткой можно делать что угодно: перетаскивать (rebase), сливать коммиты и так далее.
Можешь уточнить, что ты имеешь в виду? Пока PR нет, вроде ничего страшного от force-push не происходит

2021-06-04 13:13 UTC, evgeny-boger commented on workflow.md
> +  3. Делаем что-то в ветке. До того, как был создан PR, с веткой можно делать что угодно: перетаскивать (rebase), сливать коммиты и так далее.
да, как раз явно написать, что **можно** делать force-push, пока нет PR

2021-06-07 08:04 UTC, nikitoz236 requested changes

2021-06-07 08:04 UTC, nikitoz236 commented on workflow.md
> +    конфликтов с новым `main` (или `master`), то вливать PR можно без ревью. Правила вливания как в первом сценарии.
может написать ручками сделать git diff old-branch? убедиться что ничего не потерялось.

2021-06-07 08:04 UTC, nikitoz236 commented on workflow.md
> +принятом PR делается нажатием кнопки в интерфейсе Github, остальные же пока нужно удалить вручную. В качестве задачи для
вручную тоже кнопкой на гитхабе. кстати он недает удалять ветки связаных пр пока не будет закрыт последний.

2021-06-07 08:55 UTC, webconn commented on workflow.md
> +   потому что CI проверяет PR на корректность с учётом слияния с `main` (или `master`) _(стоит внимательно проверить, будет ли перезапущена
Да, прошивок это не касается, добавлю.
Тут дело не в мерж конфликтах, а в том, соберутся ли тесты после мержа

2021-06-07 08:57 UTC, webconn commented on workflow.md
> +  4. Создаём новый PR с новой веткой. Ссылаемся на новый PR в комментариях к старому, оставляем ссылку на старый в новом.
Ну да, во втором появится ссылка на тот, который ссылается. Хотя явно всё равно не будет видно, в связи с чем появилась ссылка: можно же просто наделать ссылок в комментариях в духе "что-то починится после мержа другого ПР"

2021-06-07 08:57 UTC, webconn commented on workflow.md
> +    конфликтов с новым `main` (или `master`), то вливать PR можно без ревью. Правила вливания как в первом сценарии.
Как подсказка для того, кто делает ребейз - да, давай допишу

2021-06-07 09:07 UTC, webconn commented on workflow.md
> +принятом PR делается нажатием кнопки в интерфейсе Github, остальные же пока нужно удалить вручную. В качестве задачи для
Да, кнопку нашёл (раньше почему-то не видел. Может, внимания не обращал, а может, новая фича).
А вот как связать два PR, не разобрался. Во всяком случае, так, чтобы он не давал удалять ветки у связанных.

2021-06-07 09:27 UTC, nikitoz236 commented on workflow.md
> +принятом PR делается нажатием кнопки в интерфейсе Github, остальные же пока нужно удалить вручную. В качестве задачи для
а ее реально нет пока висит активный пр который ссылается на данный. когда его закрываешь в старом появляется кнопка.

2021-06-07 09:29 UTC, webconn commented on workflow.md
> +принятом PR делается нажатием кнопки в интерфейсе Github, остальные же пока нужно удалить вручную. В качестве задачи для
Вот у меня в тестовом репозитории она появилась после закрытия, несмотря на то, что ссылающийся репозиторий ещё открыт.

2021-06-07 09:35 UTC, nikitoz236 requested changes
еще хочется обратить внимание, решить и зафиксировать в тексте кто нажимает кнопку мердж ? кажется что это ВСЕГДА должен делать тот кто создал пр. в таком случае он писал в описании что вливать нужно через сквош.

2021-06-07 09:35 UTC, nikitoz236 commented on workflow.md
> +   Это безопасно, потому что CI проверяет PR на корректность с учётом слияния с `main` (или `master`) _(стоит внимательно проверить, будет ли перезапущена
какоето процедурное программирование речевых конструкций ). можно же написать чтото типа ДЛЯ ВСЕГО КРОМЕ ПРОШИВОК это безопасно. для прошивок пока не работает. ато предложение начинающееся с фразы это безопасно успокаивает бдительность и до конца предложения где ограничивается зона действия утверждения можно и не дочитать

2021-06-07 09:35 UTC, nikitoz236 commented on workflow.md
> +Вариант `Squash and merge` можно выбрать, если в ветке был один коммит. **Нужно** выбрать этот вариант, если так написано
тоже предлагаю перефразировать в конструкцию если -> то
раза перечитал чтобы понять смысл. если один коммит то МОЖНО сквош. если написано в описании пр вливать чез сквош то НУЖНО сквош.
Во всех остальных - мердж коммит

2021-06-07 09:56 UTC, webconn commented
Вот по поводу того, кто нажимает Merge. Мне кажется, если в описании явно не написано, что это должен сделать автор или кто-то ещё, то можно это право оставить последнему ревьюверу. Мне кажется, это очень удобно, особенно с мелкими правками - так пакет быстрее доедет до testing. А вот в больших ответственных PR, где может быть важен порядок действий, надо явно прописывать в комментах, кто и когда должен это смержить.

2021-06-07 10:01 UTC, nikitoz236 commented
тому кто не поставил апрув непонятно нужно ли делать ребейз перед мерджем. кроме того тому что делает мердж нужно пнуть дженкинс на сборку или сделать какието еще действия. такчто я за то что мерджит создатель пр.

2021-06-07 10:09 UTC, webconn commented
Если нужно делать ребейз, то понятно, что нельзя мержить вообще, про это вроде в инструкции написано. Дженкинс обычно дёргается сам, результаты проверок даже в гитхабе видно после этого. А вот если ещё какие-то действия, то об этом можно в комментах явно написать. Ну вот не знаю, у меня очень много было маленьких ПР, которые отлично мержились без меня и от этого всем было лучше.

2021-07-02 13:53 UTC, nikitoz236 commented on workflow.md
> +    форматирование и добавлять новую логику;
Давайте вообще вынесем пункт про "исправлять форматирование" - что это делать нужно вообще только в отдельных ПР ! не мешать с изменениями касающимися функционала.

2021-07-05 09:55 UTC, evgeny-boger commented on workflow.md
> +    форматирование и добавлять новую логику;
я за

2021-07-05 09:59 UTC, nikitoz236 commented on workflow.md
> +    форматирование и добавлять новую логику;
> Если нужно делать ребейз, то понятно, что нельзя мержить вообще, про это вроде в инструкции написано. Дженкинс обычно дёргается сам, результаты проверок даже в гитхабе видно после этого. А вот если ещё какие-то действия, то об этом можно в комментах явно написать. Ну вот не знаю, у меня очень много было маленьких ПР, которые отлично мержились без меня и от этого всем было лучше.

не всегда понятно будет ли разработчик делать rebase. @evgeny-boger твое мнение ? давай отразим в документе кто нажимает мердж по умолчанию ?

2021-07-05 10:30 UTC, evgeny-boger commented on workflow.md
> +    форматирование и добавлять новую логику;
моё мнение - нажимает разработчик. Если чудесным образом ревьювер и типа старший и ответственный за проект - одим человек, то может и он сделать, если не лень. Но вообще это должна быть обязанностью разработчика.

>Ну вот не знаю, у меня очень много было маленьких ПР, которые отлично мержились без меня и от этого всем было лучше.

Мне всё-таки кажется, что неопределённость здесь страшнее и перевешивает возможные плюсы.

2021-07-20 21:12 UTC, webconn commented
Подправил по результатам обсуждения с Никитой, давайте ещё раз просмотрим и вмержим. @nikitoz236 @evgeny-boger

2021-07-23 12:44 UTC, nikitoz236 approved these changes

2021-07-28 06:47 UTC, KraPete commented on workflow.md
> +Слияние выполняет автор PR после того, как все ревьюверы поставили approve.
Помню, что обсуждали, что достаточно approve от одного. Всё таки ждём всех?

2021-08-02 10:57 UTC, webconn commented on workflow.md
> +Слияние выполняет автор PR после того, как все ревьюверы поставили approve.
Я думаю, что стоит всё же дожидаться всех, кого поставили в ревьюверы. Если кто-то реально не очень нужен (например, поставил несколько человек просто ради ускорения), на твоей совести удалить молчунов из ревьюверов и влить как есть.

2021-08-02 10:59 UTC, webconn commented on workflow.md
> +    форматирование и добавлять новую логику;
Дописал, что мерж нажимает автор PR.

2021-08-30 13:38 UTC, evgeny-boger approved these changes

2021-08-30 13:44 UTC, merged